// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zError = z.object({
  error: z.string().optional(),
});

export const zValidationError = z.object({
  message: z.string().optional(),
  errors: z.record(z.string(), z.array(z.string())).optional(),
});

export const zMessageResponse = z.object({
  message: z.string().optional(),
});

export const zPeriodStatus = z.enum(["DRAFT", "VOTING", "DONE"]);

export const zElectionCategoryType = z.enum([
  "PRESIDENT",
  "DPM",
  "FACULTY_GOVERNOR",
]);

export const zCandidateRole = z.enum(["KETUA", "WAKIL", "INDIVIDUAL"]);

export const zLoginRequestStudent = z.object({
  identifier: z.string().max(255),
  password: z.string(),
});

export const zElectionPeriod = z.object({
  id: z.uuid().optional(),
  name: z.string().optional(),
  year: z.int().optional(),
  theme_config: z.record(z.string(), z.unknown()).nullish(),
  status: zPeriodStatus.optional(),
  created_by: z.uuid().nullish(),
  created_at: z.iso.datetime().optional(),
  updated_at: z.iso.datetime().optional(),
});

export const zElectionCategory = z.object({
  id: z.uuid().optional(),
  period_id: z.uuid().optional(),
  scope_faculty_id: z.uuid().nullish(),
  type: zElectionCategoryType.optional(),
  title: z.string().optional(),
  description: z.string().nullish(),
  max_winners: z.int().optional(),
  created_at: z.iso.datetime().optional(),
  updated_at: z.iso.datetime().optional(),
});

export const zElectionSchedule = z.object({
  id: z.uuid().optional(),
  period_id: z.uuid().optional(),
  scope_faculty_id: z.uuid().optional(),
  vote_start_at: z.iso.datetime().optional(),
  vote_end_at: z.iso.datetime().optional(),
  created_at: z.iso.datetime().optional(),
  updated_at: z.iso.datetime().optional(),
});

export const zCandidate = z.object({
  id: z.uuid().optional(),
  category_id: z.uuid().optional(),
  is_empty_box: z.boolean().optional(),
  is_individual: z.boolean().optional(),
  number: z.int().optional(),
  vision: z.string().optional(),
  mission: z.string().optional(),
  photo_url: z.string().nullish(),
  photo_url_portrait: z.string().nullish(),
  photo_url_landscape: z.string().nullish(),
  created_at: z.iso.datetime().optional(),
  updated_at: z.iso.datetime().optional(),
});

export const zCandidateMember = z.object({
  id: z.uuid().optional(),
  candidate_id: z.uuid().optional(),
  name: z.string().optional(),
  nim: z.string().optional(),
  role: zCandidateRole.optional(),
});

export const zCandidateWithMembers = zCandidate.and(
  z.object({
    members: z.array(zCandidateMember).optional(),
  }),
);

export const zVoteItem = z.object({
  category_id: z.uuid(),
  candidate_id: z.uuid(),
});

export const zVoteRequest = z.object({
  votes: z.array(zVoteItem).min(1).max(10),
});

/**
 * Category type (lowercase). `faculty` maps to `FACULTY_GOVERNOR` scoped to the student's faculty.
 */
export const zCategoryTypePath = z.enum(["president", "dpm", "faculty"]);

/**
 * OK
 */
export const zGetApiHealthResponse = z.object({
  message: z.string().optional(),
});

export const zPostApiStudentAuthBody = zLoginRequestStudent;

/**
 * Login success (JWT set via HttpOnly cookie)
 */
export const zPostApiStudentAuthResponse = zMessageResponse;

/**
 * Logged out
 */
export const zPostApiStudentAuthLogoutResponse = zMessageResponse;

/**
 * Active election period
 */
export const zGetApiElectionActivePeriodResponse = zElectionPeriod;

/**
 * Voting schedule for the student's faculty
 */
export const zGetApiElectionActivePeriodScheduleResponse = zElectionSchedule;

export const zGetApiElectionActivePeriodCategoriesQuery = z.object({
  type: zElectionCategoryType.optional(),
});

/**
 * List of categories
 */
export const zGetApiElectionActivePeriodCategoriesResponse =
  z.array(zElectionCategory);

export const zGetApiElectionActivePeriodCategoriesByTypeCandidatesPath =
  z.object({
    type: z.enum(["president", "dpm", "faculty"]),
  });

/**
 * List of candidates
 */
export const zGetApiElectionActivePeriodCategoriesByTypeCandidatesResponse =
  z.array(zCandidateWithMembers);

export const zPostApiElectionActivePeriodVotesBody = zVoteRequest;

/**
 * Votes recorded
 */
export const zPostApiElectionActivePeriodVotesResponse = zMessageResponse;
